namePrefix: ocp-capi-
namespace: ocp-cluster-api

commonLabels:
  cluster.x-k8s.io/provider: "cluster-api"

resources:
- ../../config/default/namespace.yaml

bases:
- crd
- ../../config/rbac
- ../../config/manager
- webhook

patchesStrategicMerge:
# Provide customizable hook for make targets.
- ../../config/default/manager_image_patch.yaml
- ../../config/default/manager_pull_policy.yaml
# Enable webhook.
- manager_webhook_patch.yaml
# Inject certificate in the webhook definition.
- webhookcainjection_patch.yaml
# Ease the process of providing extra RBAC to the Cluster API manager for
# non SIG Cluster Lifecycle-sponsored provider subprojects by using an
# aggregated role
- ../../config/default/manager_role_aggregation_patch.yaml

configurations:
  - ../../config/default/kustomizeconfig.yaml
